### ISSUE TITLE
support integer and boolean image types

### ISSUE THREAD

**Issue by Kechil** [CARTAvis/carta-backend#868]
See CARTAvis/carta-backend#520, which was split so that the complex component could be prioritised for v3b-1.

**Comment by kswang1029** [comment]
with CASA 6.4.3.27, we cannot read integer image (eg via imhead, or the viewer). The error messages are

> 2022-03-31 01:57:37 INFO imhead	##########################################
2022-03-31 01:57:37 INFO imhead	##### Begin Task: imhead             #####
2022-03-31 01:57:37 INFO imhead	imhead( imagename='integer.image', mode='summary', hdkey='', hdvalue='', verbose=False )
2022-03-31 01:57:37 SEVERE image	Exception Reported: Exception: Unable to open image integer.image.
2022-03-31 01:57:37 SEVERE image	... thrown by static casa::ITUPLE casa::ImageFactory::fromFile(const casa6core::String &, casa6core::Bool) at File: src/code/imageanalysis/ImageAnalysis/ImageFactory2.cc, line: 289
2022-03-31 01:57:37 SEVERE imhead	Task imhead raised an exception of class RuntimeError with the following message: Exception: Unable to open image integer.image.
2022-03-31 01:57:37 SEVERE imhead	... thrown by static casa::ITUPLE casa::ImageFactory::fromFile(const casa6core::String &, casa6core::Bool) at File: src/code/imageanalysis/ImageAnalysis/ImageFactory2.cc, line: 289
2022-03-31 01:57:37 INFO imhead	Task imhead complete. Start time: 2022-03-31 09:57:36.915086 End time: 2022-03-31 09:57:36.929847
2022-03-31 01:57:37 INFO imhead	##### End Task: imhead               #####
2022-03-31 01:57:37 INFO imhead	##########################################
2022-03-31 01:57:37 SEVERE imhead	Exception Reported: Error in imhead: Exception: Unable to open image integer.image.
2022-03-31 01:57:37 SEVERE imhead	... thrown by static casa::ITUPLE casa::ImageFactory::fromFile(const casa6core::String &, casa6core::Bool) at File: src/code/imageanalysis/ImageAnalysis/ImageFactory2.cc, line: 289
2022-03-31 01:57:37 INFO imhead	Traceback (most recent call last):
2022-03-31 01:57:37 INFO imhead	  File "/Applications/CASA.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/casashell/private/imhead.py", line 414, in __call__
2022-03-31 01:57:37 INFO imhead	    _return_result_ = _imhead_t( _invocation_parameters['imagename'],_invocation_parameters['mode'],_invocation_parameters['hdkey'],_invocation_parameters['hdvalue'],_invocation_parameters['verbose'] )
2022-03-31 01:57:37 INFO imhead	  File "/Applications/CASA.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/casatasks/imhead.py", line 130, in __call__
2022-03-31 01:57:37 INFO imhead	    task_result = _imhead_t( _pc.document['imagename'], _pc.document['mode'], _pc.document['hdkey'], _pc.document['hdvalue'], _pc.document['verbose'] )
2022-03-31 01:57:37 INFO imhead	  File "/Applications/CASA.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/casatasks/private/task_imhead.py", line 114, in imhead
2022-03-31 01:57:37 INFO imhead	    myia.open(imagename)
2022-03-31 01:57:37 INFO imhead	  File "/Applications/CASA.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/casatools/image.py", line 2601, in open
2022-03-31 01:57:37 INFO imhead	    return self._swigobj.open(_str_ec(infile), cache)
2022-03-31 01:57:37 INFO imhead	  File "/Applications/CASA.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/casatools/__casac__/image.py", line 5396, in open
2022-03-31 01:57:37 INFO imhead	    return _image.image_open(self, *args, **kwargs)
2022-03-31 01:57:37 INFO imhead	RuntimeError: Exception: Unable to open image integer.image.
2022-03-31 01:57:37 INFO imhead	... thrown by static casa::ITUPLE casa::ImageFactory::fromFile(const casa6core::String &, casa6core::Bool) at File: src/code/imageanalysis/ImageAnalysis/ImageFactory2.cc, line: 289

same for boolean image

> 2022-03-31 02:00:54 INFO imhead	##########################################
2022-03-31 02:00:54 INFO imhead	##### Begin Task: imhead             #####
2022-03-31 02:00:54 INFO imhead	imhead( imagename='boolean.image', mode='summary', hdkey='', hdvalue='', verbose=False )
2022-03-31 02:00:54 SEVERE image	Exception Reported: Exception: Unable to open image boolean.image.
2022-03-31 02:00:54 SEVERE image	... thrown by static casa::ITUPLE casa::ImageFactory::fromFile(const casa6core::String &, casa6core::Bool) at File: src/code/imageanalysis/ImageAnalysis/ImageFactory2.cc, line: 289
2022-03-31 02:00:54 SEVERE imhead	Task imhead raised an exception of class RuntimeError with the following message: Exception: Unable to open image boolean.image.
2022-03-31 02:00:54 SEVERE imhead	... thrown by static casa::ITUPLE casa::ImageFactory::fromFile(const casa6core::String &, casa6core::Bool) at File: src/code/imageanalysis/ImageAnalysis/ImageFactory2.cc, line: 289
2022-03-31 02:00:54 INFO imhead	Task imhead complete. Start time: 2022-03-31 10:00:53.761360 End time: 2022-03-31 10:00:53.767064
2022-03-31 02:00:54 INFO imhead	##### End Task: imhead               #####
2022-03-31 02:00:54 INFO imhead	##########################################
2022-03-31 02:00:54 SEVERE imhead	Exception Reported: Error in imhead: Exception: Unable to open image boolean.image.
2022-03-31 02:00:54 SEVERE imhead	... thrown by static casa::ITUPLE casa::ImageFactory::fromFile(const casa6core::String &, casa6core::Bool) at File: src/code/imageanalysis/ImageAnalysis/ImageFactory2.cc, line: 289
2022-03-31 02:00:54 INFO imhead	Traceback (most recent call last):
2022-03-31 02:00:54 INFO imhead	  File "/Applications/CASA.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/casashell/private/imhead.py", line 414, in __call__
2022-03-31 02:00:54 INFO imhead	    _return_result_ = _imhead_t( _invocation_parameters['imagename'],_invocation_parameters['mode'],_invocation_parameters['hdkey'],_invocation_parameters['hdvalue'],_invocation_parameters['verbose'] )
2022-03-31 02:00:54 INFO imhead	  File "/Applications/CASA.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/casatasks/imhead.py", line 130, in __call__
2022-03-31 02:00:54 INFO imhead	    task_result = _imhead_t( _pc.document['imagename'], _pc.document['mode'], _pc.document['hdkey'], _pc.document['hdvalue'], _pc.document['verbose'] )
2022-03-31 02:00:54 INFO imhead	  File "/Applications/CASA.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/casatasks/private/task_imhead.py", line 114, in imhead
2022-03-31 02:00:54 INFO imhead	    myia.open(imagename)
2022-03-31 02:00:54 INFO imhead	  File "/Applications/CASA.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/casatools/image.py", line 2601, in open
2022-03-31 02:00:54 INFO imhead	    return self._swigobj.open(_str_ec(infile), cache)
2022-03-31 02:00:54 INFO imhead	  File "/Applications/CASA.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/casatools/__casac__/image.py", line 5396, in open
2022-03-31 02:00:54 INFO imhead	    return _image.image_open(self, *args, **kwargs)
2022-03-31 02:00:54 INFO imhead	RuntimeError: Exception: Unable to open image boolean.image.
2022-03-31 02:00:54 INFO imhead	... thrown by static casa::ITUPLE casa::ImageFactory::fromFile(const casa6core::String &, casa6core::Bool) at File: src/code/imageanalysis/ImageAnalysis/ImageFactory2.cc, line: 289

@jott3077 please advise on how you use CASA to read integer and boolean images?

**Comment by markccchiang** [comment]
I think we can try a way similar to `CartaFitsImage` that inherits the class `casacore::ImageInterface<float>` and then modify the `doGetSlice` function. Converting the integer or boolean types to float in the `doGetSlice` function when accessing images data.

**Comment by pford** [comment]
The imageanalaysis types supported ("ITUPLE" in the traceback) include float, complex, double, and complex\<double\>.  I also tried to open integer.image in the casaviewer and the message was: "Only Float and Complex images are supported at present."

**Comment by pford** [comment]
I think we need to keep the image types already in CARTA, but support the data types as `PagedImage<T>`, `CartaHdf5Image<T>`, etc. (base class `ImageInterface<T>`).

Jorge has started on this for complex images; the additional requirement for complex data is the ability for the user to request magnitude, phase, real or imaginary data.

**Comment by jolopezl** [comment]
Thanks, @pford, some of these changes are here https://github.com/CARTAvis/carta-backend/tree/520-support-complex-image-types, but they might not be the best thing to do.

**Comment by pford** [comment]
I just found out that `casacore::ImageOpener::openImage(filename)` only supports typed images of data type Float, Double, Complex, and DComplex (PagedImage, HDF5Image, ImageConcat, and ImageExpr).  It doubt this is a CASA viewer replacement item if casacore code and imageanalysis code do not support it.

I vote we close this issue.

**Comment by kswang1029** [comment]
> I just found out that `casacore::ImageOpener::openImage(filename)` only supports typed images of data type Float, Double, Complex, and DComplex (PagedImage, HDF5Image, ImageConcat, and ImageExpr). It doubt this is a CASA viewer replacement item if casacore code and imageanalysis code do not support it.
> 
> I vote we close this issue.

If CASA cannot handle boolean and integer images I also suggest we close this issue.
`ia.newimagefromarray(): Create a new image analysis tool from a numpy array.
` can only allow me to generate a float or double precision image. We cannot make an integer nor a boolean image. 
@jott3077 @jehibbard can we close this issue?

**Comment by jott3077** [comment]
The image types are CASA images, according to Kumar. Maybe they are handled differently.

**Comment by jehibbard** [comment]
I looked at a few "mask" images from the ALMA pipeline, thinking they may be integer, but CARTA had no problem opening those. So I'm not sure I know what the use case for pure integer or boolean images are.
